# 1003474
# Alex W

import hashlib

rcrack = [
    'kopi',
    'asdf',
    'cuvant',
    'zyx987',
    'lepak',
    '12345',
    'orange',
    'banana',
    '98765',
    'qwerty',
    'b1umua',
    '123456',
    'bojio',
    'donkey',
    '123123',
    'abcde',
    'makan',
    'siao5',
    'sheep',
    'abc123',
    'google',
    'alamak',
    'paiseh',
    'secret',
]

hashcat = [
    'kopi',
    'xkcd',
    'dogsandcats',
    'letmein',
    'bojio',
    'jennifer',
    '1a2b3c4d',
    'lepak',
    'h9d120313c712ici79',
    'sheep',
    'facebook',
    'skittles',
    'hunter2',
    'di5i11u5i0ni57',
    'firstname',
    'poiuytrewq',
    '@@@@@@@@@@@',
    'fidoismydog',
    '2011992',
    '123123',
    'password123',
    'mycatiscute',
    'u123731201212h4ph9',
    'alamak',
    '59873523',
    'password1234567890',
    'qwerty1234',
    'secret',
    'password',
    'bananacustard',
    'unm310di0u5n355',
    'nucleation-growth',
    '4ever&ever',
    'howareyou1',
    'qwertyuiop',
    'banana',
    'television',
    'ofir123',
    'password1',
    'nintendo',
    'cuvant',
    'treasure',
    '12345',
    'skeleton',
    'dragon',
    'security1',
    'tr0mb0n3',
    'asdf',
    'randombits',
    'donkey',
    'zyx987',
    'MaidenName',
    'AcH98',
    'genghis',
    'disease-clustering',
    'ilovepapa!',
    'abcde',
    'kamikaze123',
    'drowssap',
    '98765',
    'bubbles1980',
    'google',
    'Geezin a bit of dee gee',
    '3.1415926535',
    'makan',
    'qwerty',
    'tulmultuous',
    'PENGUINS71',
    'paiseh',
    'rickrolled',
    'yellowfellow',
    '123456',
    'abc123',
    'let me in',
    'external auditory meatus',
    'hello123',
    'Cara123',
    'orange',
]
john = [
    '59873523',
    'security1',
    '2011992',
    'abcde',
    'banana',
    'randombits',
    'orange',
    'vladkool',
    'alamak',
    'makan',
    'hunter2',
    'skittles',
    'bubbles1980',
    'treasure',
    'google',
    'mycatiscute',
    'password1',
    'skeleton',
    'zyx987',
    'kopi',
    'genghis',
    'abc123',
    'H3!!0',
    'asdf',
    '12345',
    '123456',
    'donkey',
    'password',
    'sheep',
    'qwertyuiop',
    'drowssap',
    'facebook',
    'Cara123',
    'letmein',
    'secret',
    'jennifer',
    'television',
    'paiseh',
    '98765',
    'xkcd',
    'cuvant',
    'siao5',
    'hellen1989',
    'qwerty',
    'hello123',
    'nintendo',
    'lepak',
    'firstname',
    'kiasu00',
    'ofir123',
    'dragon',
    'bojio',
    'password123',
    '123123',
    'howareyou1',
    'tr0mb0n3',
    'poiuytrewq',
    'AcH98',
    'm@k@n',
    '1a2b3c4d',
    'b1umua',
    'dogsandcats',
    '12secret123',
    'jac0b!',
    '$eLLer',
    'b6o0r8b6',
    'Chjklm88',
]

combined_plaintext_list = list(
    set(rcrack).union(set(hashcat)).union(set(john)))
print(len(combined_plaintext_list))

hashed_list = []

for plaintext in combined_plaintext_list:
    hashed = hashlib.md5(plaintext.encode()).hexdigest()
    hashed_list.append(hashed)

with open('hashes_2.txt', 'r') as f1:
    hashes_2 = f1.readlines()
    with open('hashes_2.csv', 'w+') as f2:
        for hash_current in hashes_2:
            hash_current = hash_current.rstrip('\n')
            index = -1
            output = ""
            try:
                index = hashed_list.index(hash_current)
                output = f'{hash_current},{combined_plaintext_list[index]}\n'
            except ValueError:
                output = f'{hash_current},NIL\n'
            finally:
                print(output)
                f2.write(output)